

#include <QtGlobal>

// Automatically generated by extract_strings.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *bitcoin_strings[] = {
QT_TRANSLATE_NOOP("anime-core", ""
"(1 = keep tx meta data e.g. account owner and payment request information, 2 "
"= drop tx meta data)"),
QT_TRANSLATE_NOOP("anime-core", ""
"-maxtxfee is set very high! Fees this large could be paid on a single "
"transaction."),
QT_TRANSLATE_NOOP("anime-core", ""
"A fee rate (in %s/kB) that will be used when fee estimation has insufficient "
"data (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Accept relayed transactions received from whitelisted peers even when not "
"relaying transactions (default: %d)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Allow JSON-RPC connections from specified source. Valid for <ip> are a "
"single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or "
"a network/CIDR (e.g. 1.2.3.4/24). This option can be specified multiple times"),
QT_TRANSLATE_NOOP("anime-core", ""
"Bind to given address and always listen on it. Use [host]:port notation for "
"IPv6"),
QT_TRANSLATE_NOOP("anime-core", ""
"Bind to given address and whitelist peers connecting to it. Use [host]:port "
"notation for IPv6"),
QT_TRANSLATE_NOOP("anime-core", ""
"Bind to given address to listen for JSON-RPC connections. Use [host]:port "
"notation for IPv6. This option can be specified multiple times (default: "
"bind to all interfaces)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Cannot obtain a lock on data directory %s. %s is probably already running."),
QT_TRANSLATE_NOOP("anime-core", ""
"Cannot upgrade a non HD split wallet without upgrading to support pre split "
"keypool. Please use -upgradewallet=100000 or -upgradewallet with no version "
"specified."),
QT_TRANSLATE_NOOP("anime-core", ""
"Create new files with system default permissions, instead of umask 077 (only "
"effective with disabled wallet functionality)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Delete all wallet transactions and only recover those parts of the "
"blockchain through -rescan on startup"),
QT_TRANSLATE_NOOP("anime-core", ""
"Discover own IP addresses (default: 1 when listening and no -externalip or -"
"proxy)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Distributed under the MIT/X11 software license, see the accompanying file "
"COPYING."),
QT_TRANSLATE_NOOP("anime-core", ""
"Do not keep transactions in the mempool longer than <n> hours (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Error loading %s: You can't enable HD on a already existing non-HD wallet"),
QT_TRANSLATE_NOOP("anime-core", ""
"Error reading %s! All keys read correctly, but transaction data or address "
"book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("anime-core", ""
"Error: Listening for incoming connections failed (listen returned error %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Error: Unsupported argument -socks found. Setting SOCKS version isn't "
"possible anymore, only SOCKS5 proxies are supported."),
QT_TRANSLATE_NOOP("anime-core", ""
"Execute command when a relevant alert is received or we see a really long "
"fork (%s in cmd is replaced by message)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Execute command when a wallet transaction changes (%s in cmd is replaced by "
"TxID)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Execute command when the best block changes (%s in cmd is replaced by block "
"hash)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Fees (in %s/kB) smaller than this are considered zero fee for relaying, "
"mining and transaction creation (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Fees (in %s/kB) smaller than this are considered zero fee for transaction "
"creation (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Force relay of transactions from whitelisted peers even they violate local "
"relay policy (default: %d)"),
QT_TRANSLATE_NOOP("anime-core", ""
"How thorough the block verification of -checkblocks is (0-4, default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"If paytxfee is not set, include enough fee so transactions begin "
"confirmation on average within n blocks (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"If this block is in the chain assume that it and its ancestors are valid and "
"potentially skip their script verification (0 to verify all, default: %s, "
"testnet: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Invalid amount for -maxtxfee=<amount>: '%s' (must be at least the minrelay "
"fee of %s to prevent stuck transactions)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Location of the auth cookie. Relative paths will be prefixed by a net-"
"specific datadir location. (default: data dir)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Maintain a full transaction index, used by the getrawtransaction rpc call "
"(default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Maximum size of data in data carrier transactions we relay and mine "
"(default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Maximum total fees (in %s) to use in a single wallet transaction or raw "
"transaction; setting this too low may abort large transactions (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Number of seconds to keep misbehaving peers from reconnecting (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Output debugging information (default: %u, supplying <category> is optional)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Prune configured below the minimum of %d MiB.  Please use a higher number."),
QT_TRANSLATE_NOOP("anime-core", ""
"Prune: last wallet synchronisation goes beyond pruned data. You need to -"
"reindex (download the whole blockchain again in case of pruned node)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Query for peer addresses via DNS lookup, if low on addresses (default: 1 "
"unless -connect)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Randomize credentials for every proxy connection. This enables Tor stream "
"isolation (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Reduce storage requirements by enabling pruning (deleting) of old blocks. "
"This allows the pruneblockchain RPC to be called to delete specific blocks, "
"and enables automatic pruning of old blocks if a target size in MiB is "
"provided. This mode is incompatible with -txindex and -rescan. Warning: "
"Reverting this setting requires re-downloading the entire blockchain. "
"(default: 0 = disable pruning blocks, 1 = allow manual pruning via RPC, >%u "
"= automatically prune block files to stay under the specified target size in "
"MiB)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Rescans are not possible in pruned mode. You will need to use -reindex which "
"will download the whole blockchain again."),
QT_TRANSLATE_NOOP("anime-core", ""
"Set lowest fee rate (in %s/kB) for transactions to be included in block "
"creation. (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Set maximum size of high-priority/low-fee transactions in bytes (default: %d)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Set the number of script verification threads (%u to %d, 0 = auto, <0 = "
"leave that many cores free, default: %d)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Specify configuration file. Relative paths will be prefixed by datadir "
"location. (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Specify location of debug log file. Relative paths will be prefixed by a net-"
"specific datadir location. (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Specify pid file. Relative paths will be prefixed by a net-specific datadir "
"location. (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Support filtering of blocks and transaction with bloom filters (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Tell other nodes to filter invs to us by our mempool min fee (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", ""
"The block database contains a block which appears to be from the future. "
"This may be due to your computer's date and time being set incorrectly. Only "
"rebuild the block database if you are sure that your computer's date and "
"time are correct"),
QT_TRANSLATE_NOOP("anime-core", ""
"The transaction amount is too small to send after the fee has been deducted"),
QT_TRANSLATE_NOOP("anime-core", ""
"This is a pre-release test build - use at your own risk - do not use for "
"mining or merchant applications"),
QT_TRANSLATE_NOOP("anime-core", ""
"This is the transaction fee you may pay when fee estimates are not available."),
QT_TRANSLATE_NOOP("anime-core", ""
"Tries to keep outbound traffic under the given target (in MiB per 24h), 0 = "
"no limit (default: %d)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Unable to bind to %s on this computer. Animecoin is probably already running."),
QT_TRANSLATE_NOOP("anime-core", ""
"Unable to replay blocks. You will need to rebuild the database using -"
"reindex-chainstate."),
QT_TRANSLATE_NOOP("anime-core", ""
"Unsupported argument -whitelistalwaysrelay ignored, use -whitelistrelay and/"
"or -whitelistforcerelay."),
QT_TRANSLATE_NOOP("anime-core", ""
"Use UPnP to map the listening port (default: 1 when listening and no -proxy)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Use hierarchical deterministic key generation (HD) after bip32. Only has "
"effect during wallet creation/first start"),
QT_TRANSLATE_NOOP("anime-core", ""
"Use separate SOCKS5 proxy to reach peers via Tor hidden services (default: "
"%s)"),
QT_TRANSLATE_NOOP("anime-core", ""
"Username and hashed password for JSON-RPC connections. The field <userpw> "
"comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is "
"included in share/rpcuser. This option can be specified multiple times"),
QT_TRANSLATE_NOOP("anime-core", ""
"Wallet will not create transactions that violate mempool chain limits "
"(default: %u"),
QT_TRANSLATE_NOOP("anime-core", ""
"Warning: Please check that your computer's date and time are correct! If "
"your clock is wrong Animecoin will not work properly."),
QT_TRANSLATE_NOOP("anime-core", ""
"Warning: The network does not appear to fully agree! Some miners appear to "
"be experiencing issues."),
QT_TRANSLATE_NOOP("anime-core", ""
"Warning: Wallet file corrupt, data salvaged! Original %s saved as %s in %s; "
"if your balance or transactions are incorrect you should restore from a "
"backup."),
QT_TRANSLATE_NOOP("anime-core", ""
"Warning: We do not appear to fully agree with our peers! You may need to "
"upgrade, or other nodes may need to upgrade."),
QT_TRANSLATE_NOOP("anime-core", ""
"Whitelist peers connecting from the given netmask or IP address. Can be "
"specified multiple times."),
QT_TRANSLATE_NOOP("anime-core", ""
"Whitelisted peers cannot be DoS banned and their transactions are always "
"relayed, even if they are already in the mempool, useful e.g. for a gateway"),
QT_TRANSLATE_NOOP("anime-core", ""
"You need to rebuild the database using -reindex to go back to unpruned "
"mode.  This will redownload the entire blockchain"),
QT_TRANSLATE_NOOP("anime-core", ""
"You need to rebuild the database using -reindex-chainstate to change -txindex"),
QT_TRANSLATE_NOOP("anime-core", "%s corrupt, salvage failed"),
QT_TRANSLATE_NOOP("anime-core", "%s is set very high!"),
QT_TRANSLATE_NOOP("anime-core", "(default: %s)"),
QT_TRANSLATE_NOOP("anime-core", "(default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "-wallet parameter must only specify a filename (not a path)"),
QT_TRANSLATE_NOOP("anime-core", "<category> can be:"),
QT_TRANSLATE_NOOP("anime-core", "Accept command line and JSON-RPC commands"),
QT_TRANSLATE_NOOP("anime-core", "Accept connections from outside (default: 1 if no -proxy or -connect)"),
QT_TRANSLATE_NOOP("anime-core", "Accept public REST requests (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Add a node to connect to and attempt to keep the connection open"),
QT_TRANSLATE_NOOP("anime-core", "Allow DNS lookups for -addnode, -seednode and -connect"),
QT_TRANSLATE_NOOP("anime-core", "Always query for peer addresses via DNS lookup (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Append comment to the user agent string"),
QT_TRANSLATE_NOOP("anime-core", "Attempt to recover private keys from a corrupt wallet on startup"),
QT_TRANSLATE_NOOP("anime-core", "Automatically create Tor hidden service (default: %d)"),
QT_TRANSLATE_NOOP("anime-core", "Block creation options:"),
QT_TRANSLATE_NOOP("anime-core", "Cannot downgrade wallet"),
QT_TRANSLATE_NOOP("anime-core", "Cannot resolve -%s address: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Change index out of range"),
QT_TRANSLATE_NOOP("anime-core", "Connect only to the specified node(s)"),
QT_TRANSLATE_NOOP("anime-core", "Connect through SOCKS5 proxy"),
QT_TRANSLATE_NOOP("anime-core", "Connect to a node to retrieve peer addresses, and disconnect"),
QT_TRANSLATE_NOOP("anime-core", "Connection options:"),
QT_TRANSLATE_NOOP("anime-core", "Copyright (C) 2009-%i The Bitcoin and Anime Developers"),
QT_TRANSLATE_NOOP("anime-core", "Corrupted block database detected"),
QT_TRANSLATE_NOOP("anime-core", "Debugging/Testing options:"),
QT_TRANSLATE_NOOP("anime-core", "Do not load the wallet and disable wallet RPC calls"),
QT_TRANSLATE_NOOP("anime-core", "Do you want to rebuild the block database now?"),
QT_TRANSLATE_NOOP("anime-core", "Done loading"),
QT_TRANSLATE_NOOP("anime-core", "Enable publish hash block in <address>"),
QT_TRANSLATE_NOOP("anime-core", "Enable publish hash transaction in <address>"),
QT_TRANSLATE_NOOP("anime-core", "Enable publish raw block in <address>"),
QT_TRANSLATE_NOOP("anime-core", "Enable publish raw transaction in <address>"),
QT_TRANSLATE_NOOP("anime-core", "Error initializing block database"),
QT_TRANSLATE_NOOP("anime-core", "Error initializing wallet database environment %s!"),
QT_TRANSLATE_NOOP("anime-core", "Error loading %s"),
QT_TRANSLATE_NOOP("anime-core", "Error loading %s: Wallet corrupted"),
QT_TRANSLATE_NOOP("anime-core", "Error loading %s: Wallet requires newer version of %s"),
QT_TRANSLATE_NOOP("anime-core", "Error loading %s: You can't disable HD on a already existing HD wallet"),
QT_TRANSLATE_NOOP("anime-core", "Error loading block database"),
QT_TRANSLATE_NOOP("anime-core", "Error opening block database"),
QT_TRANSLATE_NOOP("anime-core", "Error reading from database, shutting down."),
QT_TRANSLATE_NOOP("anime-core", "Error upgrading chainstate database"),
QT_TRANSLATE_NOOP("anime-core", "Error"),
QT_TRANSLATE_NOOP("anime-core", "Error: -maxmempool must be at least %d MB"),
QT_TRANSLATE_NOOP("anime-core", "Error: A fatal internal error occured, see debug.log for details"),
QT_TRANSLATE_NOOP("anime-core", "Error: A fatal internal error occurred, see debug.log for details"),
QT_TRANSLATE_NOOP("anime-core", "Error: Disk space is low!"),
QT_TRANSLATE_NOOP("anime-core", "Error: Unsupported argument -tor found, use -onion."),
QT_TRANSLATE_NOOP("anime-core", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("anime-core", "Fee (in %s/kB) to add to transactions you send (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", "How many blocks to check at startup (default: %u, 0 = all)"),
QT_TRANSLATE_NOOP("anime-core", "If <category> is not supplied, output all debugging information."),
QT_TRANSLATE_NOOP("anime-core", "Importing..."),
QT_TRANSLATE_NOOP("anime-core", "Imports blocks from external blk000??.dat file"),
QT_TRANSLATE_NOOP("anime-core", "Include IP addresses in debug output (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Incorrect or no genesis block found. Wrong datadir for network?"),
QT_TRANSLATE_NOOP("anime-core", "Information"),
QT_TRANSLATE_NOOP("anime-core", "Initialization sanity check failed. %s is shutting down."),
QT_TRANSLATE_NOOP("anime-core", "Insufficient funds"),
QT_TRANSLATE_NOOP("anime-core", "Invalid -onion address: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Invalid -proxy address: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Invalid amount for -%s=<amount>: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Invalid amount for -fallbackfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Invalid amount for -paytxfee=<amount>: '%s' (must be at least %s)"),
QT_TRANSLATE_NOOP("anime-core", "Invalid characters in -wallet filename"),
QT_TRANSLATE_NOOP("anime-core", "Invalid netmask specified in -whitelist: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Keep at most <n> unconnectable transactions in memory (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Keep the transaction memory pool below <n> megabytes (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Light client mode is incompatible with -txindex."),
QT_TRANSLATE_NOOP("anime-core", "Listen for JSON-RPC connections on <port> (default: %u or testnet: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Listen for connections on <port> (default: %u or testnet: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Loading addresses..."),
QT_TRANSLATE_NOOP("anime-core", "Loading banlist..."),
QT_TRANSLATE_NOOP("anime-core", "Loading block index..."),
QT_TRANSLATE_NOOP("anime-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("anime-core", "Maintain at most <n> connections to peers (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Make the wallet broadcast transactions"),
QT_TRANSLATE_NOOP("anime-core", "Maximum per-connection receive buffer, <n>*1000 bytes (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Maximum per-connection send buffer, <n>*1000 bytes (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Minimum bytes per sigop in transactions we relay and mine (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Need to specify a port with -whitebind: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Node relay options:"),
QT_TRANSLATE_NOOP("anime-core", "Not enough file descriptors available."),
QT_TRANSLATE_NOOP("anime-core", "Only connect to nodes in network <net> (ipv4, ipv6 or onion)"),
QT_TRANSLATE_NOOP("anime-core", "Options:"),
QT_TRANSLATE_NOOP("anime-core", "Password for JSON-RPC connections"),
QT_TRANSLATE_NOOP("anime-core", "Permit transaction replacement (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Prepend debug output with timestamp (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Print this help message and exit"),
QT_TRANSLATE_NOOP("anime-core", "Print version and exit"),
QT_TRANSLATE_NOOP("anime-core", "Prune cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("anime-core", "Pruning blockstore..."),
QT_TRANSLATE_NOOP("anime-core", "RPC server options:"),
QT_TRANSLATE_NOOP("anime-core", "Rebuild chain state and block index from the blk*.dat files on disk"),
QT_TRANSLATE_NOOP("anime-core", "Rebuild chain state from the currently indexed blocks"),
QT_TRANSLATE_NOOP("anime-core", "Receive and display P2P network alerts (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Reducing -maxconnections from %d to %d, because of system limitations."),
QT_TRANSLATE_NOOP("anime-core", "Relay and mine data carrier transactions (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Relay non-P2SH multisig (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Replaying blocks..."),
QT_TRANSLATE_NOOP("anime-core", "Rescan the block chain for missing wallet transactions on startup"),
QT_TRANSLATE_NOOP("anime-core", "Rescanning..."),
QT_TRANSLATE_NOOP("anime-core", "Run in the background as a daemon and accept commands"),
QT_TRANSLATE_NOOP("anime-core", "Send trace/debug info to console instead of debug.log file"),
QT_TRANSLATE_NOOP("anime-core", "Send transactions as zero-fee transactions if possible (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Send transactions with full-RBF opt-in enabled (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Set database cache size in megabytes (%d to %d, default: %d)"),
QT_TRANSLATE_NOOP("anime-core", "Set key pool size to <n> (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Set maximum block size in bytes (default: %d)"),
QT_TRANSLATE_NOOP("anime-core", "Set minimum block size in bytes (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Set the number of threads to service RPC calls (default: %d)"),
QT_TRANSLATE_NOOP("anime-core", "Show all debugging options (usage: --help -help-debug)"),
QT_TRANSLATE_NOOP("anime-core", "Shrink debug.log file on client startup (default: 1 when no -debug)"),
QT_TRANSLATE_NOOP("anime-core", "Signing transaction failed"),
QT_TRANSLATE_NOOP("anime-core", "Specify connection timeout in milliseconds (minimum: 1, default: %d)"),
QT_TRANSLATE_NOOP("anime-core", "Specify data directory"),
QT_TRANSLATE_NOOP("anime-core", "Specify wallet file (within data directory)"),
QT_TRANSLATE_NOOP("anime-core", "Specify your own public address"),
QT_TRANSLATE_NOOP("anime-core", "Spend unconfirmed change when sending transactions (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Starting network threads..."),
QT_TRANSLATE_NOOP("anime-core", "The transaction amount is too small to pay the fee"),
QT_TRANSLATE_NOOP("anime-core", "The wallet will avoid paying less than the minimum relay fee."),
QT_TRANSLATE_NOOP("anime-core", "This is experimental software."),
QT_TRANSLATE_NOOP("anime-core", "This is the minimum transaction fee you pay on every transaction."),
QT_TRANSLATE_NOOP("anime-core", "This is the transaction fee you will pay if you send a transaction."),
QT_TRANSLATE_NOOP("anime-core", "Threshold for disconnecting misbehaving peers (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Tor control port password (default: empty)"),
QT_TRANSLATE_NOOP("anime-core", "Tor control port to use if onion listening enabled (default: %s)"),
QT_TRANSLATE_NOOP("anime-core", "Transaction amount too small"),
QT_TRANSLATE_NOOP("anime-core", "Transaction amounts must be positive"),
QT_TRANSLATE_NOOP("anime-core", "Transaction has too long of a mempool chain"),
QT_TRANSLATE_NOOP("anime-core", "Transaction too large for fee policy"),
QT_TRANSLATE_NOOP("anime-core", "Transaction too large"),
QT_TRANSLATE_NOOP("anime-core", "Unable to bind to %s on this computer (bind returned error %s)"),
QT_TRANSLATE_NOOP("anime-core", "Unable to generate initial keys"),
QT_TRANSLATE_NOOP("anime-core", "Unable to generate keys"),
QT_TRANSLATE_NOOP("anime-core", "Unable to start HTTP server. See debug log for details."),
QT_TRANSLATE_NOOP("anime-core", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("anime-core", "Upgrade wallet to latest format on startup"),
QT_TRANSLATE_NOOP("anime-core", "Upgrading UTXO database"),
QT_TRANSLATE_NOOP("anime-core", "Use UPnP to map the listening port (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Use full block spv before validating the chain (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Username for JSON-RPC connections"),
QT_TRANSLATE_NOOP("anime-core", "Verifying blocks..."),
QT_TRANSLATE_NOOP("anime-core", "Verifying wallet..."),
QT_TRANSLATE_NOOP("anime-core", "Wallet debugging/testing options:"),
QT_TRANSLATE_NOOP("anime-core", "Wallet needed to be rewritten: restart %s to complete"),
QT_TRANSLATE_NOOP("anime-core", "Wallet options:"),
QT_TRANSLATE_NOOP("anime-core", "Warning"),
QT_TRANSLATE_NOOP("anime-core", "Warning: This version is obsolete, upgrade required!"),
QT_TRANSLATE_NOOP("anime-core", "Warning: Unsupported argument -benchmark ignored, use -debug=bench."),
QT_TRANSLATE_NOOP("anime-core", "Warning: Unsupported argument -debugnet ignored, use -debug=net."),
QT_TRANSLATE_NOOP("anime-core", "Whether to operate in a blocks only mode (default: %u)"),
QT_TRANSLATE_NOOP("anime-core", "Zapping all transactions from wallet..."),
QT_TRANSLATE_NOOP("anime-core", "ZeroMQ notification options:"),
QT_TRANSLATE_NOOP("anime-core", "on startup"),
};
